allowBuilds:
  "@doublekekse/find-java": true
  "tomate-launcher-core": true
  "tomate-mods": true
  tomate-loaders: true
  "@swc/core": true
  electron: true
  electron-winstaller: true
  esbuild: true
