name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

permissions:
  contents: write


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v6


      - name: build project
        uses: ./.github/actions/build
        with:
          publish: always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
